[book]
authors = ["20syldev"]
language = "en"
multilingual = false
src = "src"
title = "Coop - Bot Discord - Wiki"
description = "GitHub officiel du Wiki Coop Bot qui explique les commandes, les utilisations et les caractéristiques de Coop."

[output.html]
theme = "src/theme"
default-theme = "coop"
preferred-dark-theme = "coop"
git-repository-url = "https://github.com/20syldev/doc-coopbot"
input-404 = "./404.md"
site-url = "/doc-coopbot/"
edit-url-template = "https://github.com/20syldev/doc-coopbot/edit/dev/{path}"

[output.html.search]
boost-title = 4  

[output.html.fold]
enable = true
level = 0
