name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "v*"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "20syldev/doc-coopbot@v0.9.9-b"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true