name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "v*"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases/latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true